// Generated by Selenium IDE
import io.qameta.allure.Description;
import io.qameta.allure.Feature;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.MatcherAssert.assertThat;

@Feature("添加新闻成功")
public class AddNewsSuccessTest extends BaseTest{

  @Test
  @Description("添加新闻成功")
  public void addNewsSuccess() {
    this.logIn();
    driver.findElement(By.cssSelector(".is-active")).click();
    driver.findElement(By.cssSelector(".el-menu-item:nth-child(5) > span")).click();
    driver.findElement(By.cssSelector(".table-title-button > .el-button--primary")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".table-title-button > .el-button--primary"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector(".el-form-item__content .el-input__inner")).click();
    driver.findElement(By.cssSelector(".el-form-item__content .el-input__inner")).sendKeys("testNews");
    driver.findElement(By.cssSelector(".el-col-12:nth-child(1)")).click();
    driver.findElement(By.cssSelector(".el-textarea__inner")).click();
    driver.findElement(By.cssSelector(".el-textarea__inner")).sendKeys("this is a test");
    driver.findElement(By.cssSelector(".el-button--primary:nth-child(2)")).click();
    WebDriverWait wait = new WebDriverWait(driver,10);
    wait.until(ExpectedConditions.visibilityOfElementLocated(By.cssSelector("p")));
    assertThat(driver.findElement(By.cssSelector("p")).getText(), is("添加成功"));

    assertThat(driver.findElement(By.cssSelector(".el-table__row:nth-child(1) > .el-table_2_column_8 > .cell")).getText(), is("testNews"));
    assertThat(driver.findElement(By.cssSelector(".el-table__row:nth-child(1) > .el-table_2_column_9 span")).getText(), is("this is a test"));

  }
}
