// Generated by Selenium IDE
import io.qameta.allure.*;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.MatcherAssert.assertThat;

@Feature("添加新闻失败场景")
public class AddNewsFailedTest extends BaseTest{

  @Test
  @Description("输入内容为空，弹出信息：输入格式不正确")
  public void addNewsFailedOne() {
    //输入为空
    this.logIn();
    driver.findElement(By.cssSelector(".is-active > span")).click();
    driver.findElement(By.cssSelector(".el-menu-item:nth-child(5) > span")).click();
    driver.findElement(By.cssSelector(".table-title-button > .el-button--primary > span")).click();
    driver.findElement(By.cssSelector(".el-form-item__content .el-input__inner")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".el-button--primary:nth-child(2) > span"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector(".el-button--primary:nth-child(2) > span")).click();
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    assertThat(driver.findElement(By.cssSelector(".el-message__content")).getText(), is("输入格式不正确！"));
  }

  @Test
  @Description("输入字符串长度过长，弹出信息：添加失败")
  public void addNewsFailedTwo(){
    //长度过长
    this.logIn();
    String title = BaseTest.generateString(60);
    String content = BaseTest.generateString(1010);
    driver.findElement(By.cssSelector(".is-active")).click();
    driver.findElement(By.cssSelector(".el-menu-item:nth-child(5) > span")).click();
    driver.findElement(By.cssSelector(".table-title-button > .el-button--primary")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".table-title-button > .el-button--primary"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector(".el-form-item__content .el-input__inner")).click();
    driver.findElement(By.cssSelector(".el-form-item__content .el-input__inner")).sendKeys(title);
    driver.findElement(By.cssSelector(".el-col-12:nth-child(1)")).click();
    driver.findElement(By.cssSelector(".el-textarea__inner")).click();
    driver.findElement(By.cssSelector(".el-textarea__inner")).sendKeys(content);
    driver.findElement(By.cssSelector(".el-button--primary:nth-child(2)")).click();
    WebDriverWait wait = new WebDriverWait(driver,10);
    wait.until(ExpectedConditions.visibilityOfElementLocated(By.cssSelector("p")));
    assertThat(driver.findElement(By.cssSelector("p")).getText(), is("添加失败"));
  }
}
