// Generated by Selenium IDE
import io.qameta.allure.Feature;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.MatcherAssert.assertThat;

@Feature("审核通过留言成功")
public class ApproveMessageSuccessTest extends BaseTest{
  @Test
  public void approveMessageSuccess() {
    this.logIn();
    driver.findElement(By.cssSelector(".is-active")).click();
    driver.findElement(By.cssSelector(".el-menu-item:nth-child(6)")).click();
    driver.findElement(By.cssSelector(".el-table__row:nth-child(1) .el-checkbox__inner")).click();
    driver.findElement(By.cssSelector(".table-title-button span")).click();
    {
      WebDriverWait wait = new WebDriverWait(driver, 30);
      wait.until(ExpectedConditions.visibilityOfElementLocated(By.cssSelector(".el-message-box__content")));
    }
    assertThat(driver.findElement(By.cssSelector(".el-message-box__content")).getText(), is("审核通过成功"));
    driver.findElement(By.cssSelector(".el-button--default > span")).click();
  }
}
