// Generated by Selenium IDE

import io.qameta.allure.Feature;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.support.ui.ExpectedConditions;

import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.MatcherAssert.assertThat;

@Feature("审核通过订单成功")
public class ApproveOrderSuccessTest extends BaseTest{

  @Test
  public void approveOrderSuccess() {
    this.logIn();
    driver.findElement(By.cssSelector(".is-active > .el-icon-tickets")).click();
    driver.findElement(By.cssSelector(".el-menu-item:nth-child(2) > span")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".el-table__row:nth-child(1) > .el-table_2_column_6 > .cell"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".el-table__row:nth-child(1) .el-checkbox__original"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    driver.findElement(By.cssSelector(".el-table__row:nth-child(1) .el-checkbox__inner")).click();
    driver.findElement(By.cssSelector(".table-title-button > .el-button")).click();
    WebDriverWait wait = new WebDriverWait(driver,10);
    wait.until(ExpectedConditions.visibilityOfElementLocated(By.cssSelector("p")));
    assertThat(driver.findElement(By.cssSelector("p")).getText(), is("审核通过成功"));
    driver.findElement(By.cssSelector(".el-button--default > span")).click();
  }
}
