// Generated by Selenium IDE
import org.junit.jupiter.api.Test;
import static org.hamcrest.MatcherAssert.assertThat;
import org.openqa.selenium.By;

public class CheckOrderStatisticTest extends BaseTest{

  @Test
  public void checkOrderStatistic() {
    this.logIn();
    driver.findElement(By.cssSelector(".is-active")).click();
    driver.findElement(By.cssSelector(".el-menu-item:nth-child(3) > span")).click();
    driver.findElement(By.cssSelector(".el-input__inner")).click();
    driver.findElement(By.cssSelector(".el-icon-arrow-left")).click();
    driver.findElement(By.cssSelector(".el-icon-arrow-left")).click();
    driver.findElement(By.cssSelector(".el-date-table__row:nth-child(3) > .available:nth-child(5) span")).click();
    driver.findElement(By.cssSelector(".el-input__inner")).click();
    driver.findElement(By.cssSelector(".el-date-table__row:nth-child(6) > .available:nth-child(1) span")).click();
    driver.findElement(By.cssSelector(".el-input__inner")).click();
    driver.findElement(By.cssSelector(".el-date-table__row:nth-child(6) > .available:nth-child(3) span")).click();
  }
}
