// Generated by Selenium IDE

import io.qameta.allure.Description;
import io.qameta.allure.Feature;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;

import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.MatcherAssert.assertThat;

@Feature("修改密码成功")
public class CorrectModifyPasswordTest extends BaseTest{
  @Test
  @Description("弹出信息：修改密码成功")
  public void correctModifyPassword() {
    this.logIn();
    driver.findElement(By.cssSelector(".el-icon-arrow-down")).click();
    driver.findElement(By.cssSelector(".el-icon-arrow-down")).click();
    WebElement element = driver.findElement(By.cssSelector(".el-icon-arrow-down"));
    Actions builder = new Actions(driver);
    builder.moveToElement(element).perform();
    try{
      Thread.sleep(1200);
    }
    catch (InterruptedException e)
    {
      e.printStackTrace();
    }
    driver.findElement(By.cssSelector(".el-dropdown-menu__item:nth-child(1)")).click();
    driver.findElement(By.cssSelector(".el-row:nth-child(2) .el-input__inner")).click();
    driver.findElement(By.cssSelector(".el-row:nth-child(2) .el-input__inner")).sendKeys("Rua33@");
    driver.findElement(By.cssSelector(".el-row:nth-child(2) .el-input__icon")).click();
    driver.findElement(By.cssSelector(".el-row:nth-child(3) .el-input__inner")).click();
    driver.findElement(By.cssSelector(".el-row:nth-child(3) .el-input__inner")).sendKeys("Rua33@");
    driver.findElement(By.cssSelector(".el-row:nth-child(4) .el-input__inner")).click();
    driver.findElement(By.cssSelector(".el-row:nth-child(4) .el-input__inner")).sendKeys("Rua33@");
    driver.findElement(By.cssSelector("div:nth-child(1) > .el-button--primary")).click();
    assertThat(driver.findElement(By.cssSelector("p")).getText(), is("修改密码成功"));
    driver.findElement(By.cssSelector(".el-button--small > span")).click();
  }
}
