// Generated by Selenium IDE
import org.junit.jupiter.api.Test;
import static org.hamcrest.MatcherAssert.assertThat;
import static org.hamcrest.CoreMatchers.is;

import org.openqa.selenium.By;

import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;

public class CorrectLogOutTest extends BaseTest{
  //todo
  @Test
  public void correctLogOut() {
    driver.get("http://localhost:8080/user/main");
    driver.manage().window().setSize(new Dimension(864, 755));
    driver.findElement(By.cssSelector(".el-menu-item:nth-child(7)")).click();
    driver.findElement(By.cssSelector(".el-button--text > span")).click();
    driver.findElement(By.cssSelector(".el-form-item:nth-child(1) .el-input__inner")).click();
    driver.findElement(By.cssSelector(".el-form-item:nth-child(1) .el-input__inner")).sendKeys("ballballtang");
    driver.findElement(By.cssSelector(".el-input--suffix > .el-input__inner")).sendKeys("rua");
    {
      WebElement element = driver.findElement(By.cssSelector(".el-button"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector(".el-button")).click();
    driver.findElement(By.cssSelector(".el-icon-arrow-down")).click();
    driver.findElement(By.cssSelector(".el-icon-arrow-down")).click();
    driver.findElement(By.cssSelector(".el-dropdown-menu__item:nth-child(2)")).click();
    assertThat(driver.findElement(By.id("h2")).getText(), is("管理员登录"));
  }
}
