// Generated by Selenium IDE

import io.qameta.allure.Feature;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;

import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.MatcherAssert.assertThat;

@Feature("正确登录")
public class CorrectLogInTest extends BaseTest{
  @Test
  public void correctLogIn() {
    driver.get("http://localhost:8080/user/main");
    driver.manage().window().setSize(new Dimension(864, 752));
    driver.findElement(By.cssSelector(".el-menu-item:nth-child(7)")).click();
    driver.findElement(By.cssSelector(".el-button--text > span")).click();
    assertThat(driver.findElement(By.id("h2")).getText(), is("管理员登录"));
    driver.findElement(By.cssSelector(".el-form-item:nth-child(1) .el-input__inner")).click();
    driver.findElement(By.cssSelector(".el-form-item:nth-child(1) .el-input__inner")).sendKeys("ballballtang");
    driver.findElement(By.cssSelector(".el-input--suffix > .el-input__inner")).click();
    driver.findElement(By.cssSelector(".el-input--suffix > .el-input__inner")).sendKeys("Rua33@");
    driver.findElement(By.cssSelector(".el-icon-view")).click();
    driver.findElement(By.cssSelector(".el-button")).click();
    driver.findElement(By.cssSelector(".el-main")).click();
    driver.findElement(By.cssSelector(".el-icon-arrow-down")).click();
    driver.findElement(By.cssSelector(".el-icon-arrow-down")).click();
    assertThat(driver.findElement(By.id("managerName")).getText(), is("ballballtang"));
  }
}
