// Generated by Selenium IDE

import io.qameta.allure.Description;
import io.qameta.allure.Feature;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;

import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.MatcherAssert.assertThat;

@Feature("正常注销用户")
public class CorrectLogOutTest extends BaseTest{
  @Test
  @Description("页面自动跳转到登录页面，且无法进入管理员端其他页面")
  public void correctLogOut() {
    this.logIn();
    driver.findElement(By.cssSelector(".el-icon-arrow-down")).click();
    driver.findElement(By.cssSelector(".el-icon-arrow-down")).click();
    WebElement element = driver.findElement(By.cssSelector(".el-icon-arrow-down"));
    Actions builder = new Actions(driver);
    builder.moveToElement(element).perform();
    try{
      Thread.sleep(2000);
    }
    catch (InterruptedException e)
    {
      e.printStackTrace();
    }
    driver.findElement(By.cssSelector(".el-dropdown-menu__item:nth-child(2)")).click();
    assertThat(driver.findElement(By.id("h2")).getText(), is("管理员登录"));
  }
}
