// Generated by Selenium IDE
import org.junit.jupiter.api.Test;
import static org.hamcrest.MatcherAssert.assertThat;
import static org.hamcrest.CoreMatchers.is;
import org.openqa.selenium.By;


public class GoToUrlTest extends BaseTest{

  @Test
  public void goToUrl() {
    this.logIn();
    assertThat(driver.findElement(By.cssSelector("h2")).getText(), is("用户信息"));
    driver.findElement(By.cssSelector(".el-menu-item:nth-child(2) > span")).click();
    assertThat(driver.findElement(By.cssSelector("h2")).getText(), is("预约订单审核"));
    driver.findElement(By.cssSelector(".el-menu-item:nth-child(3) > span")).click();
    assertThat(driver.findElement(By.cssSelector("h2")).getText(), is("预约订单统计信息"));
    driver.findElement(By.cssSelector(".el-menu-item:nth-child(4) > span")).click();
    assertThat(driver.findElement(By.cssSelector("h2")).getText(), is("场馆信息管理"));
    driver.findElement(By.cssSelector(".el-menu-item:nth-child(5) > span")).click();
    assertThat(driver.findElement(By.cssSelector("h2")).getText(), is("新闻动态管理"));
    driver.findElement(By.cssSelector(".el-menu-item:nth-child(6) > span")).click();
    driver.findElement(By.cssSelector("h2")).click();
    assertThat(driver.findElement(By.cssSelector("h2")).getText(), is("留言审核"));
  }
}
