// Generated by Selenium IDE
import io.qameta.allure.Feature;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.MatcherAssert.assertThat;

@Feature("修改场馆信息成功")
public class ModifyVenueSuccessTest extends BaseTest{

  @Test
  public void modifyVenueSuccess() {
    this.logIn();
    driver.findElement(By.cssSelector(".is-active > span")).click();
    driver.findElement(By.cssSelector(".el-menu-item:nth-child(4) > span")).click();
    driver.findElement(By.cssSelector(".el-table__row:nth-child(1) > .el-table_2_column_12 span")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".el-table__row:nth-child(1) > .el-table_2_column_12 span"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector(".el-form-item__content .el-input__inner")).click();
    driver.findElement(By.cssSelector(".el-form-item__content .el-input__inner")).clear();
    driver.findElement(By.cssSelector(".el-form-item__content .el-input__inner")).sendKeys("100");
    driver.findElement(By.cssSelector(".el-textarea__inner")).click();
    driver.findElement(By.cssSelector(".el-textarea__inner")).clear();
    driver.findElement(By.cssSelector(".el-textarea__inner")).sendKeys("This is a venue to test modify venue venue.");
    driver.findElement(By.cssSelector(".el-dialog__footer:nth-child(3) .el-button--primary")).click();
    //wait for the backend
    WebDriverWait wait = new WebDriverWait(driver,10);
    wait.until(ExpectedConditions.visibilityOfElementLocated(By.cssSelector("p")));
    assertThat(driver.findElement(By.cssSelector("p")).getText(), is("修改成功"));
    driver.findElement(By.cssSelector(".el-button--small > span")).click();
  }
}
