// Generated by Selenium IDE
import io.qameta.allure.Feature;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.MatcherAssert.assertThat;

@Feature("修改新闻成功")
public class ModifyNewsSuccessTest extends BaseTest{

  @Test
  public void modifyNewsSuccess() {
    this.logIn();
    driver.findElement(By.cssSelector(".is-active")).click();
    driver.findElement(By.cssSelector(".el-menu-item:nth-child(5)")).click();
    driver.findElement(By.cssSelector(".el-table__row:nth-child(1) .el-button:nth-child(1) > span")).click();
    driver.findElement(By.cssSelector(".el-form-item__content .el-input__inner")).click();
    driver.findElement(By.cssSelector(".el-form-item__content .el-input__inner")).click();
    driver.findElement(By.cssSelector(".el-form-item__content .el-input__inner")).clear();
    driver.findElement(By.cssSelector(".el-form-item__content .el-input__inner")).sendKeys("ruaruarua");
    driver.findElement(By.cssSelector(".el-textarea__inner")).click();
    driver.findElement(By.cssSelector(".el-textarea__inner")).clear();
    driver.findElement(By.cssSelector(".el-textarea__inner")).sendKeys("wulawulawula");
    driver.findElement(By.cssSelector(".el-button--primary:nth-child(2) > span")).click();

    WebDriverWait wait = new WebDriverWait(driver,10);
    wait.until(ExpectedConditions.visibilityOfElementLocated(By.cssSelector("p")));

    assertThat(driver.findElement(By.cssSelector("p")).getText(), is("修改成功"));
    driver.findElement(By.cssSelector(".el-message-box__btns span")).click();
  }
}
