// Generated by Selenium IDE
import io.qameta.allure.Description;
import io.qameta.allure.Feature;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.MatcherAssert.assertThat;

@Feature("修改新闻失败")
public class ModifyNewsFailedTest extends BaseTest{
  @Test
  @Description("输入字符串过长，弹出信息：修改失败")
  public void modifyNewsFailed() {
    this.logIn();
    String title = BaseTest.generateString(60);
    String content = BaseTest.generateString(1100);
    driver.findElement(By.cssSelector(".is-active")).click();
    driver.findElement(By.cssSelector(".el-menu-item:nth-child(5)")).click();
    driver.findElement(By.cssSelector(".el-table__row:nth-child(1) .el-button:nth-child(1) > span")).click();
    driver.findElement(By.cssSelector(".el-form-item__content .el-input__inner")).click();
    driver.findElement(By.cssSelector(".el-form-item__content .el-input__inner")).click();
    driver.findElement(By.cssSelector(".el-form-item__content .el-input__inner")).clear();
    driver.findElement(By.cssSelector(".el-form-item__content .el-input__inner")).sendKeys(title);
    driver.findElement(By.cssSelector(".el-textarea__inner")).click();
    driver.findElement(By.cssSelector(".el-textarea__inner")).clear();
    driver.findElement(By.cssSelector(".el-textarea__inner")).sendKeys(content);
    driver.findElement(By.cssSelector(".el-button--primary:nth-child(2) > span")).click();

    WebDriverWait wait = new WebDriverWait(driver,10);
    wait.until(ExpectedConditions.visibilityOfElementLocated(By.cssSelector("p")));

    assertThat(driver.findElement(By.cssSelector("p")).getText(), is("修改失败"));
  }
}
