// Generated by Selenium IDE
import io.qameta.allure.Feature;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;

import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.MatcherAssert.assertThat;

@Feature("搜索场馆成功")
public class SearchVenueSuccessTest extends BaseTest{

  @Test
  public void searchVenueSuccess() {
    this.logIn();
    driver.findElement(By.cssSelector(".el-menu-item:nth-child(4) > span")).click();
    driver.findElement(By.cssSelector(".el-col > .el-input > .el-input__inner")).click();
    driver.findElement(By.cssSelector(".el-col > .el-input > .el-input__inner")).sendKeys("2");
    driver.findElement(By.cssSelector(".el-col-8 span")).click();
    assertThat(driver.findElement(By.cssSelector(".el-table_2_column_7 span")).getText(), is("2"));
  }
}
