// Generated by Selenium IDE
import org.junit.jupiter.api.Test;
import static org.hamcrest.MatcherAssert.assertThat;
import static org.hamcrest.CoreMatchers.is;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;

public class SearchOrderSuccessTest extends BaseTest{

  @Test
  public void searchOrderSuccess() {
    this.logIn();
    driver.findElement(By.cssSelector(".el-menu-item:nth-child(2) > span")).click();
    driver.findElement(By.cssSelector(".el-menu-item:nth-child(1) > span")).click();
    driver.findElement(By.cssSelector(".el-menu-item:nth-child(2) > span")).click();
    driver.findElement(By.cssSelector(".el-col > .el-input > .el-input__inner")).click();
    driver.findElement(By.cssSelector(".el-col > .el-input > .el-input__inner")).sendKeys("2");
    driver.findElement(By.cssSelector(".el-col-24")).click();
    driver.findElement(By.cssSelector(".el-col-8 > .el-button")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".el-col-8 > .el-button"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    assertThat(driver.findElement(By.cssSelector(".el-table__row > .el-table_4_column_21 > .cell")).getText(), is("2"));
  }
}
