// Generated by Selenium IDE

import io.qameta.allure.Description;
import io.qameta.allure.Feature;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;

import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.MatcherAssert.assertThat;

@Feature("搜索用户失败")
public class SearchUserFailedTest extends BaseTest{

  @Test
  @Description("未输入搜索信息，弹出信息：请输入搜索内容！")
  public void searchUserWrongOne() {
    this.logIn();
    driver.findElement(By.cssSelector(".el-col > .el-input > .el-input__inner")).click();
    driver.findElement(By.cssSelector(".el-col-8 span")).click();
    assertThat(driver.findElement(By.cssSelector(".el-message__content")).getText(), is("请输入搜索内容！"));

  }
  @Test
  @Description("输入的ID数据库不存在，弹出信息:搜索失败")
  public void searchUserWrongTwo() {
    this.logIn();

    driver.findElement(By.cssSelector(".el-col > .el-input > .el-input__inner")).click();
    driver.findElement(By.cssSelector(".el-col > .el-input > .el-input__inner")).sendKeys("5465132");
    driver.findElement(By.cssSelector(".el-col-8 > .el-button")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".el-col-8 > .el-button"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    assertThat(driver.findElement(By.cssSelector(".el-message")).getText(), is("搜索失败"));

  }
}
