// Generated by Selenium IDE

import io.qameta.allure.Feature;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;

import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.MatcherAssert.assertThat;

@Feature("搜索用户成功")
public class SearchUserSuccessTest extends BaseTest{

  @Test
  public void searchUserSuccess() {
    this.logIn();
    driver.findElement(By.cssSelector(".el-col > .el-input > .el-input__inner")).click();
    driver.findElement(By.cssSelector(".el-col > .el-input > .el-input__inner")).click();
    driver.findElement(By.cssSelector(".el-col > .el-input > .el-input__inner")).sendKeys("3");
    driver.findElement(By.cssSelector(".el-col-8 > .el-button")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".el-col-8 > .el-button"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    assertThat(driver.findElement(By.cssSelector(".el-table__row > .el-table_1_column_2 > .cell")).getText(), is("3"));
  }
}
