// Generated by Selenium IDE
import io.qameta.allure.Description;
import io.qameta.allure.Feature;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.MatcherAssert.assertThat;

@Feature("搜索留言失败")
public class SearchMessageFailedTest extends BaseTest{

  @Test
  @Description("未输入搜索内容，弹出信息：请输入搜索内容！")
  public void messageSearchFailedOne() {
    this.logIn();
    driver.findElement(By.cssSelector(".is-active > span")).click();
    driver.findElement(By.cssSelector(".el-menu-item:nth-child(6)")).click();
    driver.findElement(By.cssSelector(".el-col > .el-input > .el-input__inner")).click();
    driver.findElement(By.cssSelector(".el-col-8 > .el-button")).click();
    assertThat(driver.findElement(By.cssSelector(".el-message__content")).getText(), is("请输入搜索内容！"));

  }

  @Test
  @Description("输入的ID不在数据库内，弹出信息：搜索失败！")
  public void messageSearchFailedTwo(){
    this.logIn();
    driver.findElement(By.cssSelector(".is-active > span")).click();
    driver.findElement(By.cssSelector(".el-menu-item:nth-child(6)")).click();
    driver.findElement(By.cssSelector(".el-col > .el-input > .el-input__inner")).click();
    driver.findElement(By.cssSelector(".el-col > .el-input > .el-input__inner")).sendKeys("2654");
    driver.findElement(By.cssSelector(".el-col-8 > .el-button")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".el-col-8 > .el-button"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    WebDriverWait wait = new WebDriverWait(driver,10);
    wait.until(ExpectedConditions.visibilityOfElementLocated(By.cssSelector(".el-message__content")));
    assertThat(driver.findElement(By.cssSelector(".el-message__content")).getText(), is("搜索失败"));
  }
}
