// Generated by Selenium IDE
import io.qameta.allure.Description;
import io.qameta.allure.Feature;
import org.junit.jupiter.api.Test;
import static org.hamcrest.CoreMatchers.is;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

import java.util.List;

import static org.hamcrest.MatcherAssert.assertThat;

@Feature("查看新闻图片失败")
public class ViewPictureFailedTest extends BaseTest{

  @Test
  @Description("测试的数据是第一条新闻，必须没有图片，否则测试失败。弹出信息：该条新闻没有图片")
  public void viewPictureFailed() {
    this.logIn();
    driver.findElement(By.cssSelector(".is-active > span")).click();
    driver.findElement(By.cssSelector(".el-menu-item:nth-child(5) > span")).click();
    driver.findElement(By.cssSelector(".el-table__row:nth-child(1) .el-button:nth-child(2) > span")).click();
    //todo 测试的是第一条新闻，第一条新闻必须没有图片否则测试失败
    List<WebElement> elements = driver.findElements(By.cssSelector(".el-message"));
    if(elements.size() > 0){
      assertThat(driver.findElement(By.cssSelector(".el-message__content")).getText(), is("该条新闻没有图片"));
    }else{
      System.out.println("测试的新闻是第一条，所以第一条新闻必须有图片");
    }

  }
}
