// Generated by Selenium IDE

import io.qameta.allure.Description;
import io.qameta.allure.Feature;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.By;

import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.MatcherAssert.assertThat;

@Feature("错误地删除用户")
public class WrongDeleteUserTest extends BaseTest{

  @Test
  @Description("未选中用户点击删除按钮，弹出信息：选中数量为0条")
  public void wrongDeleteUser() {
    this.logIn();
    driver.findElement(By.cssSelector(".el-button--danger > span")).click();
    assertThat(driver.findElement(By.cssSelector(".el-message")).getText(), is("选中数量为0条"));
  }
}
