// Generated by Selenium IDE

import io.qameta.allure.Description;
import io.qameta.allure.Feature;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;

import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.MatcherAssert.assertThat;

@Feature("错误地修改密码，确认密码不一致")
public class WrongModifyPasswordOneTest extends BaseTest{
  //新密码和确认密码不一致
  @Test
  @Description("弹出信息：两次密码不一致")
  public void wrongModifyPasswordOne() {
    this.logIn();
    //driver.findElement(By.cssSelector(".el-icon-arrow-down")).click();
    WebElement element = driver.findElement(By.cssSelector(".el-icon-arrow-down"));
    Actions builder = new Actions(driver);
    builder.moveToElement(element).perform();
    try{
      Thread.sleep(1200);
    }
    catch (InterruptedException e)
    {
      e.printStackTrace();
    }
    driver.findElement(By.cssSelector(".el-dropdown-menu__item:nth-child(1)")).click();
    driver.findElement(By.cssSelector(".el-row:nth-child(2) .el-input__inner")).click();
    driver.findElement(By.cssSelector(".el-row:nth-child(2) .el-input__inner")).sendKeys("rua");
    driver.findElement(By.cssSelector(".el-row:nth-child(2) .el-input__icon")).click();
    driver.findElement(By.cssSelector(".el-row:nth-child(3) .el-input__inner")).click();
    driver.findElement(By.cssSelector(".el-row:nth-child(3) .el-input__inner")).sendKeys("asd");
    driver.findElement(By.cssSelector(".el-row:nth-child(4) .el-input__inner")).click();
    driver.findElement(By.cssSelector(".el-row:nth-child(4) .el-input__inner")).sendKeys("asdasd");
    driver.findElement(By.cssSelector("div:nth-child(1) > .el-button--primary")).click();
    assertThat(driver.findElement(By.cssSelector(".el-message__content")).getText(), is("两次密码不一致"));
    driver.findElement(By.cssSelector(".el-dialog__close")).click();
  }
}
