// Generated by Selenium IDE
import io.qameta.allure.Description;
import io.qameta.allure.Feature;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;

import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.MatcherAssert.assertThat;

@Feature("错误地审核留言")
public class WrongApproveMessageTest extends BaseTest{

  @Test
  @Description("未选中留言点击审核通过按键，弹出信息：选中数量为0条")
  public void wrongApproveMessage() {
    this.logIn();
    driver.findElement(By.cssSelector(".is-active")).click();
    driver.findElement(By.cssSelector(".el-menu-item:nth-child(6) > span")).click();
    driver.findElement(By.cssSelector(".table-title-button span")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".table-title-button span"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    assertThat(driver.findElement(By.cssSelector(".el-message")).getText(), is("选中数量为0条"));
  }
}
