// Generated by Selenium IDE

import io.qameta.allure.Description;
import io.qameta.allure.Feature;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;

import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.MatcherAssert.assertThat;

@Feature("错误地升级用户")
public class WrongUpgradeUserTest extends BaseTest{

  @Test
  @Description("测试数据为第一行，第一行必须是管理员。弹出信息：该用户已经是管理员！")
  public void wrongUpgradeUser() {
    this.logIn();
    driver.findElement(By.cssSelector(".el-table__row:nth-child(1) > .el-table_1_column_3 > .cell")).click();
    //todo 第1行一定是管理员
    assertThat(driver.findElement(By.cssSelector(".el-table__row:nth-child(1) > .el-table_1_column_4 > .cell")).getText(), is("Admin"));
    driver.findElement(By.cssSelector(".el-table__row:nth-child(1) > .el-table_1_column_5 span")).click();
    if(driver.findElement(By.cssSelector(".el-message__content")).getText().equals("升级用户为管理员成功")){
      System.out.println("第一行数据必须是管理员！");
    }else {
      assertThat(driver.findElement(By.cssSelector(".el-message__content")).getText(), is("该用户已经是管理员！"));
    }
  }
}
