// Generated by Selenium IDE
import org.junit.jupiter.api.Test;
import static org.hamcrest.MatcherAssert.assertThat;
import static org.hamcrest.CoreMatchers.is;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
public class WrongUpgradeUserTest extends BaseTest{

  @Test
  public void wrongUpgradeUser() {
    driver.get("http://localhost:8080/user/main");
    driver.manage().window().setSize(new Dimension(864, 790));
    driver.findElement(By.cssSelector(".el-menu-item:nth-child(7)")).click();
    driver.findElement(By.cssSelector(".el-button--text > span")).click();
    driver.findElement(By.cssSelector(".el-form-item:nth-child(1) > .el-form-item__label")).click();
    driver.findElement(By.cssSelector(".el-form-item:nth-child(1) .el-input__inner")).click();
    driver.findElement(By.cssSelector(".el-form-item:nth-child(1) .el-input__inner")).sendKeys("ballballtang");
    driver.findElement(By.cssSelector(".el-input--suffix > .el-input__inner")).sendKeys("rua");
    driver.findElement(By.cssSelector(".el-button > span")).click();
    driver.findElement(By.cssSelector(".el-table__row:nth-child(1) > .el-table_1_column_3 > .cell")).click();
    assertThat(driver.findElement(By.cssSelector(".el-table__row:nth-child(1) > .el-table_1_column_4 > .cell")).getText(), is("Admin"));
    driver.findElement(By.cssSelector(".el-table__row:nth-child(1) > .el-table_1_column_5 span")).click();
    assertThat(driver.findElement(By.cssSelector(".el-message__content")).getText(), is("该用户已经是管理员！"));
  }
}
