// Generated by Selenium IDE

import io.qameta.allure.Description;
import io.qameta.allure.Feature;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.By;

import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.MatcherAssert.assertThat;

@Feature("错误地审核订单")
public class WrongApproveOrderTest extends BaseTest{

  @Test
  @Description("未选中订单点击审核通过按钮，弹出信息：选中数量为0条")
  public void wrongApproveOrder() {
    this.logIn();
    driver.findElement(By.cssSelector(".is-active")).click();
    driver.findElement(By.cssSelector(".el-menu-item:nth-child(2) > span")).click();
    driver.findElement(By.cssSelector(".table-title-button span")).click();
    assertThat(driver.findElement(By.cssSelector(".el-message")).getText(), is("选中数量为0条"));
  }
}
