// Generated by Selenium IDE
import io.qameta.allure.Description;
import io.qameta.allure.Feature;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.By;

import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.MatcherAssert.assertThat;

@Feature("错误地删除新闻")
public class WrongDeleteNewsTest extends BaseTest{

  @Test
  @Description("未选中新闻点击删除按钮，弹出信息：选中数量为0条")
  public void wrongDeleteNews() {
    this.logIn();
    driver.findElement(By.cssSelector(".is-active > span")).click();
    driver.findElement(By.cssSelector(".el-menu-item:nth-child(5)")).click();
    driver.findElement(By.cssSelector(".el-button--danger")).click();
    assertThat(driver.findElement(By.cssSelector(".el-message__content")).getText(), is("选中数量为0条"));
  }
}
