// Generated by Selenium IDE
import org.junit.jupiter.api.Test;
import static org.hamcrest.MatcherAssert.assertThat;
import static org.hamcrest.CoreMatchers.is;
import org.openqa.selenium.By;

public class WrongDeleteUserTest extends BaseTest{

  @Test
  public void wrongDeleteUser() {
    this.logIn();
    driver.findElement(By.cssSelector(".el-button--danger > span")).click();
    assertThat(driver.findElement(By.cssSelector(".el-message")).getText(), is("选中数量为0条"));
  }
}
