server:
  port: 8081
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    max-connections: 20000
  connection-timeout: 5000

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/meethere?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: software-testing
    password: ecnu_pig4
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/meethere?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
#    username: root
#    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true