server:
  port: 8081

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://49.235.124.124:3306/meethere?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: software-testing
    password: ecnu_pig4
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true