// Generated by Selenium IDE
import org.junit.jupiter.api.Test;
import static org.hamcrest.MatcherAssert.assertThat;
import static org.hamcrest.CoreMatchers.is;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;

public class WrongApproveOrderTest extends BaseTest{

  @Test
  public void wrongApproveOrder() {
    this.logIn();
    driver.findElement(By.cssSelector(".is-active")).click();
    driver.findElement(By.cssSelector(".el-menu-item:nth-child(2) > span")).click();
    driver.findElement(By.cssSelector(".table-title-button span")).click();
    assertThat(driver.findElement(By.cssSelector(".el-message")).getText(), is("选中数量为0条"));
  }
}
