// Generated by Selenium IDE
import org.junit.jupiter.api.Test;
import static org.hamcrest.MatcherAssert.assertThat;
import static org.hamcrest.CoreMatchers.is;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;

public class WrongModifyPasswordTwoTest extends BaseTest{
  //todo
  @Test
  public void wrongModifyPasswordTwo() {
    driver.get("http://localhost:8080/user/main");
    driver.manage().window().setSize(new Dimension(864, 700));
    driver.findElement(By.cssSelector(".el-menu-item:nth-child(7)")).click();
    driver.findElement(By.cssSelector(".el-button--text")).click();
    driver.findElement(By.cssSelector(".el-form-item:nth-child(1) .el-input__inner")).click();
    driver.findElement(By.cssSelector(".el-form-item:nth-child(1) .el-input__inner")).sendKeys("ballballtang");
    driver.findElement(By.cssSelector(".el-input--suffix > .el-input__inner")).sendKeys("rua");
    driver.findElement(By.cssSelector(".el-button")).click();
    driver.findElement(By.id("managerName")).click();
    driver.findElement(By.cssSelector(".el-dropdown-menu__item:nth-child(1)")).click();
    driver.findElement(By.cssSelector(".el-row:nth-child(2) .el-input__inner")).click();
    driver.findElement(By.cssSelector(".el-row:nth-child(2) .el-input__inner")).sendKeys("ruarua");
    driver.findElement(By.cssSelector(".el-row:nth-child(2) .el-input__icon")).click();
    driver.findElement(By.cssSelector(".el-row:nth-child(3)")).click();
    driver.findElement(By.cssSelector(".el-row:nth-child(3) .el-input__inner")).click();
    driver.findElement(By.cssSelector(".el-row:nth-child(3) .el-input__inner")).sendKeys("aaaa");
    driver.findElement(By.cssSelector(".el-row:nth-child(4) .el-input__inner")).click();
    driver.findElement(By.cssSelector(".el-row:nth-child(4) .el-input__inner")).sendKeys("aaaa");
    driver.findElement(By.cssSelector("div:nth-child(1) > .el-button--primary > span")).click();
    assertThat(driver.findElement(By.cssSelector(".el-message__content")).getText(), is("修改密码失败，用户名与密码不匹配"));
  }
}
